# Generated by Django 6.0 on 2025-12-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fafarun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=255)),
                ('gameName', models.CharField(max_length=255)),
                ('tagLine', models.CharField(max_length=5)),
            ],
        ),
    ]
