# Generated by Django 6.0 on 2025-12-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fafarun', '0002_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='tagLine',
            new_name='gameTag',
        ),
    ]
