# Generated by Django 6.0 on 2025-12-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fafarun', '0003_rename_tagline_player_gametag'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='summonerId',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
