# Generated by Django 6.0 on 2025-12-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fafarun', '0004_player_summonerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='summonerId',
        ),
    ]
