# Generated by Django 6.0 on 2025-12-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fafarun', '0005_remove_player_summonerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('RAYANE', 'Rayane'), ('ERWAN', 'Erwan'), ('NEFF', 'Neff'), ('ZIZOU', 'Zizou')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='puuid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
