# Generated by Django 6.0 on 2025-12-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fafarun', '0006_player_team_alter_player_puuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lane',
            field=models.CharField(choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MID', 'Mid'), ('ADC', 'ADC'), ('SUPPORT', 'Support')], max_length=7, null=True),
        ),
    ]
