# Generated by Django 6.0 on 2025-12-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fafarun', '0007_player_lane'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='capitaine',
            field=models.BooleanField(null=True),
        ),
    ]
