# Generated by Django 6.0 on 2025-12-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fafarun', '0008_player_capitaine'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_ten_games',
            field=models.JSONField(default=list, null=True),
        ),
    ]
