# Generated by Django 6.0 on 2025-12-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fafarun', '0009_player_last_ten_games'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='last_ten_games',
            new_name='lastTenGames',
        ),
    ]
