# Generated by Django 6.0 on 2025-12-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fafarun', '0010_rename_last_ten_games_player_lasttengames'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lpSolo',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rankSolo',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tierSolo',
            field=models.CharField(blank=True, default='UNRANKED', max_length=11),
        ),
        migrations.AlterField(
            model_name='player',
            name='capitaine',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastTenGames',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
