# Generated by Django 6.0 on 2025-12-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fafarun', '0011_player_lpsolo_player_ranksolo_player_tiersolo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='lpSolo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
