# Generated by Django 6.0 on 2025-12-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fafarun', '0012_alter_player_lpsolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lossesSolo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nbGameSolo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='winrateSolo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='player',
            name='winsSolo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
