# Generated by Django 6.0 on 2025-12-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fafarun', '0013_player_lossessolo_player_nbgamesolo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='capitaine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='lane',
            field=models.CharField(blank=True, choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MID', 'Mid'), ('ADC', 'ADC'), ('SUPPORT', 'Support')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastTenGames',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='player',
            name='lossesSolo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='lpSolo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='nbGameSolo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='puuid',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='rankSolo',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, choices=[('RAYANE', 'Rayane'), ('ERWAN', 'Erwan'), ('NEFF', 'Neff'), ('ZIZOU', 'Zizou')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='winsSolo',
            field=models.IntegerField(default=0),
        ),
    ]
