# Generated by Django 6.0 on 2025-12-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fafarun', '0014_alter_player_capitaine_alter_player_lane_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rankScore',
            field=models.IntegerField(default=0),
        ),
    ]
