# Generated by Django 6.0 on 2025-12-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fafarun', '0015_player_rankscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='icon',
            field=models.IntegerField(default=0),
        ),
    ]
