# Generated by Django 6.0 on 2025-12-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fafarun', '0016_player_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='baseRankScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pointsGained',
            field=models.IntegerField(default=0),
        ),
    ]
